package com.example.service

import java.util.Locale

/**
 * Local Consensus Arbitrator & System 2 Deliberation Engine:
 * Acts as an on-device "Critic & Verifier" that evaluates the fast, intuitive candidate thoughts
 * generated by the Local Neural Transformer and SNN against biological ground truth
 * (Polyvagal Autonomic Balance, HTM Temporal Expectations, and Personal Adaptive Baselines).
 *
 * Implements Kahneman-inspired dual-process arbitration:
 * - System 1: Fast, reactive generative hypothesis.
 * - System 2: Deliberative verification, somatic congruence check, and cognitive harmonization.
 */
class LocalConsensusArbitrator {

    enum class VerdictType(val labelKa: String, val badgeColorHex: Long) {
        HARMONIZED_CONSENSUS("სრული ჰარმონიზებული კონსენსუსი", 0xFF00E676),
        VERIFIED_ADAPTED("დამოწმებული & ადაპტირებული", 0xFF00E5FF),
        DISSONANCE_RESOLVED("სომატური დისონანსი გადალახულია", 0xFFFFD600),
        CAUTIOUS_EXPLORATION("ფრთხილი ექსპლორაცია (დაბალი რწმენა)", 0xFFFF9100)
    }

    data class ConsensusVerdict(
        val verdictType: VerdictType,
        val system1Thought: String,
        val system2VerifiedThought: String,
        val consensusScorePct: Int,         // 0..100% agreement across all local agents
        val somaticCongruencePct: Int,      // 0..100% match with heart/pupil/respiration state
        val arbitrationExplanationKa: String,
        val deliberationSteps: List<String>,
        val isDissonanceDetected: Boolean,
        val recommendedRefinement: String
    )

    /**
     * Executes the System 2 Deliberation verification loop.
     */
    fun deliberateAndArbitrate(
        system1CandidateThought: String,
        snnSnapshot: SpikingNeuralNetworkEngine.SnnTelemetrySnapshot,
        htmTelemetry: HierarchicalTemporalMemoryEngine.HtmTelemetry,
        polyvagal: PolyvagalBehavioralEngine.BehavioralAnalysisResult,
        adaptiveProfile: AdaptivePersonalProfileEngine.AdaptivePersonalProfile?,
        recalledMemory: LocalEpisodicMemoryGraph.MemoryRecallResult?,
        focusLevel: Float,
        emotionalEntropy: Float
    ): ConsensusVerdict {
        val steps = mutableListOf<String>()

        // 1. Evaluate SNN Frequency & Neuromodulatory Harmony
        val snnSpikeHz = snnSnapshot.totalSpikesPerSec
        val snnCluster = snnSnapshot.dominantActiveCluster.labelKa
        steps.add("⚡ SNN შეფასება: აქტიურია $snnCluster (${snnSpikeHz.toInt()} Hz იმპულსები).")

        // 2. Evaluate HTM Temporal Anomaly Score
        val htmAnomaly = htmTelemetry.anomalyScore
        val isSequenceExpected = htmAnomaly < 0.45f
        if (isSequenceExpected) {
            steps.add("🧬 HTM შეფასება: მიმდევრობის ანომალია დაბალია (${(htmAnomaly * 100).toInt()}%) — აზრი ჯდება ქცევით პატერნში.")
        } else {
            steps.add("⚠️ HTM შეფასება: ანომალიის მაღალი დონე (${(htmAnomaly * 100).toInt()}%) — აღმოჩენილია კონტექსტური ნახტომი.")
        }

        // 3. Somatic Congruence Check (Polyvagal State vs Candidate Meaning)
        val somaticDissonance = polyvagal.somaticDissonanceIndex
        val flowScore = polyvagal.flowStateIndex
        val sympathetic = polyvagal.sympatheticScore
        val dorsal = polyvagal.dorsalScore

        val isHighStress = sympathetic > 0.65f
        val isDeepExhaustion = dorsal > 0.70f
        val isDeepFlow = flowScore > 0.60f

        val somaticCongruenceScore = ((1.0f - somaticDissonance * 0.6f + (if (isDeepFlow) 0.2f else 0.0f)) * 100).toInt().coerceIn(40, 99)
        steps.add("🫀 სომატური თანხვედრა: $somaticCongruenceScore% (Polyvagal დისონანსი: ${(somaticDissonance * 100).toInt()}%).")

        // 4. Personal Baseline Check
        val hrDelta = adaptiveProfile?.currentHrDeviationFromBaseline ?: 0f
        val pupilDelta = adaptiveProfile?.currentPupilDeviationFromBaselineMm ?: 0f
        if (hrDelta > 6f || pupilDelta > 0.35f) {
            steps.add("🎯 ადაპტაცია: დაფიქსირებულია ბაზისური პულსის გადახრა (Δ=${String.format(Locale.US, "%+.1f", hrDelta)} BPM).")
        }

        // 5. Associative Memory Resonance
        val memoryMatchPct = recalledMemory?.similarityScorePct ?: 50
        if (memoryMatchPct >= 70) {
            steps.add("🔮 მეხსიერების რეზონანსი: წარსულ ანალოგებთან $memoryMatchPct% თანხვედრა.")
        }

        // Determine Consensus & Verdict
        val baseConsensus = (
            (if (isSequenceExpected) 35 else 20) +
            (somaticCongruenceScore * 0.4f).toInt() +
            (if (isDeepFlow) 20 else 10) +
            (if (memoryMatchPct >= 65) 10 else 5) -
            (emotionalEntropy * 20).toInt()
        ).coerceIn(45, 99)

        val isDiscordant = somaticDissonance > 0.45f || hrDelta > 8f
        val verdictType: VerdictType
        val refinedThought: String
        val explanation: String
        val recommendedRefinement: String

        when {
            baseConsensus >= 85 && !isDiscordant -> {
                verdictType = VerdictType.HARMONIZED_CONSENSUS
                refinedThought = system1CandidateThought
                explanation = "ყველა ლოკალური ქსელი (SNN, HTM, Transformer, Polyvagal) სრულ თანხმობაშია. აზრი დამოწმებულია."
                recommendedRefinement = "გამართული კოგნიტური დინამიკა — კორექცია არ მოითხოვება."
            }
            isDiscordant && isHighStress -> {
                verdictType = VerdictType.DISSONANCE_RESOLVED
                refinedThought = if (!system1CandidateThought.contains("სტრესი") && !system1CandidateThought.contains("დაძაბულობა")) {
                    "$system1CandidateThought [ფიზიოლოგიური აგზნების კორექცია]"
                } else {
                    system1CandidateThought
                }
                explanation = "დაფიქსირდა სომატური დისონანსი: გარეგანი აზრი და შინაგანი პულსაცია განსხვავდება. მოხდა ადაპტაცია."
                recommendedRefinement = "რეკომენდებულია სუნთქვის რიტმის დასტაბილურება და ფოკუსის დამიწება."
            }
            isDeepExhaustion -> {
                verdictType = VerdictType.VERIFIED_ADAPTED
                refinedThought = "$system1CandidateThought (დაღლილობის ფონზე)"
                explanation = "დორსალური ნერვული აქტივობა მიუთითებს მენტალურ გამოფიტვაზე. აზრი ადაპტირდა ენერგიის ეკონომიის მიზნით."
                recommendedRefinement = "მოკლე შესვენება კოგნიტური რესურსის აღსადგენად."
            }
            else -> {
                verdictType = VerdictType.CAUTIOUS_EXPLORATION
                refinedThought = system1CandidateThought
                explanation = "სისტემა აკვირდება ახალ კონტექსტურ გადასვლას. ლოკალური ქსელები აგრძელებენ კალიბრაციას."
                recommendedRefinement = "მომდევნო სენსორული ტაქტის დალოდება გადაწყვეტის გასამყარებლად."
            }
        }

        steps.add("⚖️ არბიტრის ვერდიქტი: ${verdictType.labelKa} (${baseConsensus}% კონსენსუსი).")

        return ConsensusVerdict(
            verdictType = verdictType,
            system1Thought = system1CandidateThought,
            system2VerifiedThought = refinedThought,
            consensusScorePct = baseConsensus,
            somaticCongruencePct = somaticCongruenceScore,
            arbitrationExplanationKa = explanation,
            deliberationSteps = steps,
            isDissonanceDetected = isDiscordant,
            recommendedRefinement = recommendedRefinement
        )
    }
}
